### ISSUE TITLE
I got this error.

### ISSUE THREAD

**Issue by moris0903** [btc-exchange/api-example-php#1]
I'm using windows 10 and xampp-win32-7.0.32-0-VC14-installer .  
I got following error.
{"error":{"code":2001,"message":"Authorization failed"}}

**Comment by tkvedaras** [comment]
Error code said that api authorization was failed. You should check and be sure that these lines are corrects:

- https://github.com/btc-exchange/api-example-php/blob/master/api-example.php#L6
- https://github.com/btc-exchange/api-example-php/blob/master/api-example.php#L9

In first line you should provide `API-KEY` which was requested and provided by Bitmarket.
In second line you should set path of your `PRIVATE KEY` (not public!)
